### ISSUE TITLE
File Sharing ≠ Microsoft Azure Active Directory, …

### ISSUE THREAD

**Issue by Giorgetto1k** [italia/manuale-di-abilitazione-al-cloud-docs#1]
Ciao, 
al punto 4.1.3 Sostituzione o Re-purchase si parla di esempi di software SaaS  
 "File Sharing (Microsoft Azure Active Directory, …)"
o si fa un esempio di File Sharing o la categoria dovrebbe essere Modern Identity

**Comment by luciopileggi** [comment]
Grazie per la segnalazione. Abbiamo scelto di eliminare i riferimenti a specifiche soluzioni commerciali.
